import type { ConsentSetting, BrandConsent, RewardItem, TransactionLog, AgentMarketItem } from './types';

export const defaultConsentSettings: ConsentSetting[] = [
  {
    id: 'purchase',
    name: 'Purchase History',
    description: 'Itemized receipts, retailer loyalty purchases, and merchant transaction logs.',
    enabled: true,
    rewardWeight: 1.5,
  },
  {
    id: 'location',
    name: 'Location Context',
    description: 'Anonymized coarse coordinates and city-level retail zone presence.',
    enabled: true,
    rewardWeight: 1.2,
  },
  {
    id: 'identity',
    name: 'Demographic Cohorts',
    description: 'Privacy-safe age brackets, general interests, and lifestyle moments.',
    enabled: true,
    rewardWeight: 0.8,
  },
  {
    id: 'browser',
    name: 'App & Web Behavior',
    description: 'Browsing categories, page affinities, and interest classifications.',
    enabled: false,
    rewardWeight: 1.0,
  },
  {
    id: 'financial',
    name: 'Anonymized Bank Metadata',
    description: 'Aggregate merchant categories, spend thresholds, and frequency indicators.',
    enabled: false,
    rewardWeight: 2.0,
  },
];

export const defaultBrands: BrandConsent[] = [
  {
    id: 'nike',
    name: 'Nike Inc.',
    category: 'Athletic Apparel & Footwear',
    logo: '👟',
    enabled: true,
    lastAccessed: '2026-06-18 09:30',
    dataShared: ['Purchase History', 'Demographic Cohorts'],
  },
  {
    id: 'uber',
    name: 'Uber Technologies',
    category: 'Mobility & Food Delivery',
    logo: '🚗',
    enabled: true,
    lastAccessed: '2026-06-17 18:15',
    dataShared: ['Location Context', 'Demographic Cohorts'],
  },
  {
    id: 'starbucks',
    name: 'Starbucks Coffee',
    category: 'Food & Beverage',
    logo: '☕',
    enabled: true,
    lastAccessed: '2026-06-18 11:05',
    dataShared: ['Purchase History'],
  },
  {
    id: 'amazon',
    name: 'Amazon.com',
    category: 'E-commerce & Retail',
    logo: '📦',
    enabled: false,
    lastAccessed: '2026-06-12 14:20',
    dataShared: [],
  },
  {
    id: 'delta',
    name: 'Delta Air Lines',
    category: 'Travel & Hospitality',
    logo: '✈️',
    enabled: false,
    lastAccessed: '2026-06-10 10:45',
    dataShared: [],
  },
  {
    id: 'spotify',
    name: 'Spotify AB',
    category: 'Entertainment & Audio',
    logo: '🎵',
    enabled: true,
    lastAccessed: '2026-06-17 22:00',
    dataShared: ['Demographic Cohorts'],
  },
];

export const defaultRewards: RewardItem[] = [
  {
    id: 'r1',
    type: 'voucher',
    title: 'Nike Store Credit',
    description: '$15.00 Voucher for Nike Online & Retail stores.',
    amount: '$15.00',
    status: 'available',
    provider: 'Nike Inc.',
    date: '2026-06-18',
  },
  {
    id: 'r2',
    type: 'cashback',
    title: 'Aura Wallet Cashback',
    description: 'Cashback earned from sharing anonymized purchase history.',
    amount: '$8.45',
    status: 'available',
    provider: 'Data Aura platform',
    date: '2026-06-17',
  },
  {
    id: 'r3',
    type: 'voucher',
    title: 'Uber Ride Voucher',
    description: '$10.00 off your next Uber Ride or Uber Eats delivery.',
    amount: '$10.00',
    status: 'claimed',
    provider: 'Uber Technologies',
    date: '2026-06-15',
  },
  {
    id: 'r4',
    type: 'points',
    title: 'Starbucks Stars Bonus',
    description: '150 Starbucks Stars deposited directly to your account.',
    amount: '150 Stars',
    status: 'claimed',
    provider: 'Starbucks Coffee',
    date: '2026-06-16',
  },
  {
    id: 'r5',
    type: 'voucher',
    title: 'Spotify Premium 1 Month',
    description: 'Free month of Spotify Premium service.',
    amount: '$11.99 value',
    status: 'pending',
    provider: 'Spotify AB',
    date: '2026-06-18',
  },
];

export const defaultTransactionLogs: TransactionLog[] = [
  {
    id: 't1',
    brandName: 'Nike Inc.',
    dataProduct: 'Active Lifestyle cohort (Demographic + Purchase)',
    accessedAt: '2026-06-18 09:30',
    purpose: 'Personalized product catalog matching',
    rewardPaid: '$0.75',
    status: 'Authorized',
  },
  {
    id: 't2',
    brandName: 'Starbucks Coffee',
    dataProduct: 'Morning commuter habit (Purchase)',
    accessedAt: '2026-06-18 11:05',
    purpose: 'Localized beverage offer distribution',
    rewardPaid: '$0.35',
    status: 'Authorized',
  },
  {
    id: 't3',
    brandName: 'Uber Technologies',
    dataProduct: 'City commute node pattern (Location)',
    accessedAt: '2026-06-17 18:15',
    purpose: 'Ride incentive recommendation engine',
    rewardPaid: '$0.50',
    status: 'Authorized',
  },
  {
    id: 't4',
    brandName: 'Spotify AB',
    dataProduct: 'Music genre demographic cohort (Demographics)',
    accessedAt: '2026-06-17 22:00',
    purpose: 'Concert event recommendation alignment',
    rewardPaid: '$0.20',
    status: 'Authorized',
  },
  {
    id: 't5',
    brandName: 'Amazon.com',
    dataProduct: 'E-commerce purchase cohort (Denied)',
    accessedAt: '2026-06-12 14:20',
    purpose: 'Generic product feed retargeting',
    rewardPaid: '$0.00',
    status: 'Revoked',
  },
];

export const marketplaceAgents: AgentMarketItem[] = [
  {
    id: 'retail_media',
    name: 'Retail Media Agent',
    description: 'Binds brand media purchases directly to retail customer CRM segments and purchase logs within secure environments.',
    provider: 'Aura Commerce Services',
    inputs: ['Brand Intent Signals', 'Retail Purchase Logs', 'Loyalty Identifiers'],
    outputs: ['Yield Optimizations', 'Dynamic Product Insertion Recommendations'],
    cost: '0.25% of media spend',
    trustScore: 99,
    certifications: ['IAB Tech Lab Compliant', 'SOC2 Type II', 'GDPR Sealed'],
    artfCompatible: true,
  },
  {
    id: 'mmm_agent',
    name: 'MMM (Marketing Mix Modeling) Agent',
    description: 'Ingests cross-platform aggregated media spend and consented lift data to calculate optimal budget allocation models.',
    provider: 'Analytics Intelligence Corp',
    inputs: ['Historical Spend', 'Regional Sales Metrics', 'Privacy-Safe Conversions'],
    outputs: ['Budget Allocation Curve', 'ROI Forecast per Channel'],
    cost: '$450 / Month',
    trustScore: 96,
    certifications: ['SOC2 Type II', 'ISO 27001'],
    artfCompatible: true,
  },
  {
    id: 'attribution',
    name: 'Multi-Touch Attribution Agent',
    description: 'Computes privacy-safe click path contributions using cryptographic match keys and multi-party clean room techniques.',
    provider: 'Data Aura Labs',
    inputs: ['Consented Clickstreams', 'Device Cohort Hashes', 'Conversion Actions'],
    outputs: ['Weighted Conversion Credits', 'Touchpoint Lift Distribution'],
    cost: '0.15% of conversion value',
    trustScore: 98,
    certifications: ['IAB Tech Lab Compliant', 'GDPR Sealed'],
    artfCompatible: true,
  },
  {
    id: 'audience_discovery',
    name: 'Audience Discovery Agent',
    description: 'Scans the consent ledger to identify high-affinity lifestyle and purchase clusters based on seed customer profiles.',
    provider: 'Aura AI Core',
    inputs: ['Seed Customer Group', 'Consent Ledger Metadata', 'Interest Affinities'],
    outputs: ['Lookalike Audience Cohort IDs', 'Category Overlap Ratios'],
    cost: '$200 / Campaign Run',
    trustScore: 97,
    certifications: ['GDPR Compliant', 'IAB Tech Lab Compliant'],
    artfCompatible: true,
  },
  {
    id: 'creative_testing',
    name: 'Creative Testing Agent',
    description: 'Runs real-time feedback loops on minor user cohorts to rank visual banner performance before full-scale activation.',
    provider: 'Optima Creative',
    inputs: ['Creative Assets', 'Cohort Demographic Preferences', 'Engagement Feedback'],
    outputs: ['Uplift Indexes', 'Optimal Asset Combinations'],
    cost: '$300 / Batch',
    trustScore: 94,
    certifications: ['SOC2 Type I'],
    artfCompatible: true,
  },
  {
    id: 'incrementality',
    name: 'Incrementality Evaluation Agent',
    description: 'Creates randomized test and control boundaries across publisher networks to verify genuine brand lift and sales uplift.',
    provider: 'Data Aura Labs',
    inputs: ['Publisher Log Exports', 'Consented Buyer Conversions', 'Cohort Split Keys'],
    outputs: ['True Incremental Lift %', 'CAC vs Incremental CAC Charts'],
    cost: '0.20% of Campaign budget',
    trustScore: 99,
    certifications: ['IAB Tech Lab Compliant', 'MRC Accredited'],
    artfCompatible: true,
  },
  {
    id: 'geo_experiment',
    name: 'Geo Experimentation Agent',
    description: 'Coordinates isolated geo-split tests across zip codes to run conversion uplift studies with zero device identity tracking.',
    provider: 'GeoUplift Solutions',
    inputs: ['ZIP Media Spend Schedule', 'Physical Retail Transaction Logs'],
    outputs: ['Geo Lift Coefficient', 'Local Conversion Uplift Index'],
    cost: '$800 / Experiment',
    trustScore: 98,
    certifications: ['CCPA Compliant', 'GDPR Sealed'],
    artfCompatible: false,
  },
  {
    id: 'pricing_agent',
    name: 'Dynamic Pricing Optimizer Agent',
    description: 'Models price sensitivity curves per customer category to optimize profit margins without leaking individual buy rates.',
    provider: 'ValueCore AI',
    inputs: ['Anonymized Basket Total', 'Historical Elasticity Index'],
    outputs: ['Optimized Incentive Thresholds', 'Discount Recommendations'],
    cost: '$600 / Month',
    trustScore: 95,
    certifications: ['SOC2 Type II'],
    artfCompatible: true,
  },
  {
    id: 'cust_insights',
    name: 'Customer Insight Agent',
    description: 'Translates raw basket contents and retail behavior into natural language profiles explaining *why* cohorts buy.',
    provider: 'Aura AI Core',
    inputs: ['SKU Affinity Logs', 'Self-Reported Survey Intents'],
    outputs: ['Persona Archetypes', 'Brand Affinity Dashboards'],
    cost: '$150 / Persona Model',
    trustScore: 97,
    certifications: ['GDPR Compliant', 'IAB Tech Lab Compliant'],
    artfCompatible: true,
  },
  {
    id: 'survey_agent',
    name: 'Automated Survey Incentive Agent',
    description: 'Identifies high-value shoppers and auto-deploys context-specific micro-surveys in exchange for direct cash deposits.',
    provider: 'Aura Panel Systems',
    inputs: ['Shopper Cohort Filters', 'Survey Question Script'],
    outputs: ['Verified Consumer Responses', 'Payment Payout Ledger'],
    cost: '$2.00 / Completed Survey',
    trustScore: 98,
    certifications: ['ESOMAR Standard', 'GDPR Sealed'],
    artfCompatible: true,
  },
];
